# Generated by Django 3.2.5 on 2021-09-13 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmodel',
            name='content',
            field=models.TextField(max_length=100),
        ),
    ]
