# Generated by Django 3.2.5 on 2021-09-13 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_boardmodel_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmodel',
            name='content',
            field=models.TextField(),
        ),
    ]
